name: sv-assignment

x-agent: &agent
  build:
    context: ../
    dockerfile: docker/agent.Dockerfile
  depends_on:
    - controller
  networks:
    - sv_network

services:
  controller:
    container_name: sv-controller
    build:
      context: ../
      dockerfile: docker/controller.Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../configs:/app/configs
    networks:
      - sv_network

  camera:
    <<: *agent
    environment:
      - AGENT_GROUP=camera
      - AGENT_ID=camera-${COMPOSE_SERVICE_INDEX:-1}

  lidar:
    <<: *agent
    environment:
      - AGENT_GROUP=lidar
      - AGENT_ID=lidar-${COMPOSE_SERVICE_INDEX:-1}

  imu:
    <<: *agent
    environment:
      - AGENT_GROUP=imu
      - AGENT_ID=imu-${COMPOSE_SERVICE_INDEX:-1}

  sync_board:
    <<: *agent
    environment:
      - AGENT_GROUP=sync_board
      - AGENT_ID=sync_board-${COMPOSE_SERVICE_INDEX:-1}

  pc:
    <<: *agent
    environment:
      - AGENT_GROUP=pc
      - AGENT_ID=pc-${COMPOSE_SERVICE_INDEX:-1}

networks:
  sv_network:
    driver: bridge
